import keyMirror from 'keymirror';

export default keyMirror({
  DOWNLOAD_SATELLITE_DATA_ATTEMPTED: null,
  DOWNLOAD_SATELLITE_DATA_FAILED: null,
  DOWNLOAD_SATELLITE_DATA_SUCCESSFUL: null,

  GET_SATELLITE_INFO_ATTEMPTED: null,
  GET_SATELLITE_INFO_FAILED: null,
  GET_SATELLITE_INFO_SUCCESSFUL: null,

  GET_PROPOGATION_ATTEMPTED: null,
  GET_PROPOGATION_FAILED: null,
  GET_PROPOGATION_SUCCESSFUL: null,

  GET_PERIOD_PROPOGATION_ATTEMPTED: null,
  GET_PERIOD_PROPOGATION_FAILED: null,
  GET_PERIOD_PROPOGATION_SUCCESSFUL: null,

  GET_SATELLITE_IDS_ATTEMPTED: null,
  GET_SATELLITE_IDS_FAILED: null,
  GET_SATELLITE_IDS_SUCCESSFUL: null,
});